/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#f6f6f6",
        "on-secondary-fixed-variant": "#7c4100",
        "on-primary-fixed-variant": "#665500",
        "error-dim": "#b92902",
        "tertiary-fixed": "#feb246",
        "error": "#b02500",
        "on-secondary-container": "#6f3a00",
        "on-tertiary": "#fff0e3",
        "surface-container-highest": "#dbdddd",
        "secondary": "#8c4a00",
        "on-surface-variant": "#5a5c5c",
        "secondary-dim": "#7b4000",
        "on-error-container": "#520c00",
        "primary-dim": "#5e4e00",
        "on-tertiary-container": "#563500",
        "surface-container-low": "#f0f1f1",
        "tertiary-dim": "#704700",
        "on-tertiary-fixed-variant": "#623d00",
        "surface-dim": "#d3d5d5",
        "primary-fixed-dim": "#efc900",
        "tertiary-fixed-dim": "#eea439",
        "inverse-on-surface": "#9c9d9d",
        "surface-tint": "#6c5a00",
        "on-background": "#2d2f2f",
        "inverse-primary": "#ffd709",
        "tertiary-container": "#feb246",
        "surface-container-high": "#e1e3e3",
        "tertiary": "#805100",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#ffc69a",
        "inverse-surface": "#0c0f0f",
        "on-primary": "#fff2cd",
        "on-tertiary-fixed": "#3a2300",
        "on-primary-fixed": "#453900",
        "secondary-container": "#ffc69a",
        "surface-variant": "#dbdddd",
        "outline-variant": "#acadad",
        "on-error": "#ffefec",
        "on-primary-container": "#5b4b00",
        "on-secondary": "#fff0e7",
        "background": "#f6f6f6",
        "on-surface": "#2d2f2f",
        "secondary-fixed-dim": "#ffb375",
        "primary-fixed": "#ffd709",
        "error-container": "#f95630",
        "surface-bright": "#f6f6f6",
        "on-secondary-fixed": "#532a00",
        "primary-container": "#ffd709",
        "primary": "#6c5a00",
        "surface-container": "#e7e8e8",
        "outline": "#767777"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Be Vietnam Pro"],
        "label": ["Be Vietnam Pro"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
  plugins: [],
}